
/* Drop Tables */

DROP TABLE ANSWERS CASCADE CONSTRAINTS;
DROP TABLE EVENTS CASCADE CONSTRAINTS;
DROP TABLE NOTICES CASCADE CONSTRAINTS;
DROP TABLE REVIEW_COMMENT CASCADE CONSTRAINTS;
DROP TABLE ADMIN_ACCOUNTS CASCADE CONSTRAINTS;
DROP TABLE CART_ITEMS CASCADE CONSTRAINTS;
DROP TABLE ORDER_DETAIL CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_QUESTIONS CASCADE CONSTRAINTS;
DROP TABLE REVIEW_RECOMMEND_HISTORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_REVIEWS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_STOCK CASCADE CONSTRAINTS;
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE PASSWORD_HINT CASCADE CONSTRAINTS;
DROP TABLE POINTS_HISTORY CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE PASSWORD_QEUSTIONS CASCADE CONSTRAINTS;


/* sequence */

create sequence admin_account_seq nocache;
create sequence category_seq nocache;
create sequence customer_seq nocache;
create sequence event_seq nocache;
create sequence notice_seq nocache;
create sequence order_seq nocache;
create sequence password_question_seq nocache;
create sequence point_seq nocache;
create sequence product_seq nocache;
create sequence product_question_seq nocache;
create sequence product_review_seq nocache;


/* Create Tables */

CREATE TABLE ADMIN_ACCOUNTS
(
	ADMIN_ACCOUNT_NO number(7,0) NOT NULL,
	ADMIN_ACCOUNT_ID varchar2(30) NOT NULL UNIQUE,
	ADMIN_ACCOUNT_PWD varchar2(30) NOT NULL,
	PRIMARY KEY (ADMIN_ACCOUNT_NO)
);


CREATE TABLE ANSWERS
(
	ADMIN_ACCOUNT_NO number(7,0) NOT NULL,
	QEUSTION_NO number(7,0) NOT NULL,
	ANSWER_CONTENTS varchar2(1000) NOT NULL,
	CREATE_DATE date DEFAULT SYSDATE NOT NULL
);


CREATE TABLE CART_ITEMS
(
	CUSTOMER_NO number(7,0) NOT NULL,
	PRODUCT_NO number(7,0) NOT NULL,
	PRODUCT_AMOUNT number(7,0) DEFAULT 1 NOT NULL
);


CREATE TABLE CATEGORIES
(
	CATEGORY_NO number(7,0) NOT NULL,
	MAIN_CATEGORY_NO number(7,0) NOT NULL,
	CATEGOTY_NAME varchar2(100) NOT NULL,
	PRIMARY KEY (CATEGORY_NO)
);


CREATE TABLE CUSTOMERS
(
	CUSTOMER_NO number(7,0) NOT NULL,
	CUSTOMER_ID varchar2(100) NOT NULL,
	CUSTOMER_PWD varchar2(100) NOT NULL,
	CUSTOMER_NAME varchar2(100) NOT NULL,
	CUSTOMER_TEL varchar2(100) NOT NULL,
	CUSTOMER_EMAIL varchar2(100) NOT NULL,
	CUSTOMER_STATUS varchar2(30) DEFAULT '정상' NOT NULL,
	CUSTOMER_POSTCODE varchar2(30) NOT NULL,
	CUSTOMER_ADDRESS_1 varchar2(100) NOT NULL,
	CUSTOMER_ADDRESS_2 varchar2(100) NOT NULL,
	CUSTOMER_GRADE varchar2(30) DEFAULT 'BRONZE' NOT NULL,
	CUSTOMER_POINT number(7,0) DEFAULT 0,
	CREATE_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (CUSTOMER_NO)
);


CREATE TABLE EVENTS
(
	EVENT_NO number(7,0) NOT NULL,
	ADMIN_ACCOUNT_NO number(7,0) NOT NULL,
	EVENT_SUBJECT varchar2(300) NOT NULL,
	EVENT_BANNER varchar2(30) NOT NULL,
	EVENT_CONTENTS varchar2(1000) NOT NULL,
	EVENT_START_DATE date NOT NULL,
	EVENT_END_DATE date NOT NULL,
	EVENT_VIEWCOUNT number(7,0) DEFAULT 0 NOT NULL,
	EVENT_STATUS varchar2(30) DEFAULT '정상',
	CREATE_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (EVENT_NO)
);


CREATE TABLE NOTICES
(
	NOTICE_NO number(7,0) NOT NULL,
	ADMIN_ACCOUNT_NO number(7,0) NOT NULL,
	NOTICE_SUBJECT varchar2(300) NOT NULL,
	NOTICE_CONTENTS varchar2(1000) NOT NULL,
	NOTICE_VIEWCOUNT number(7,0) DEFAULT 0 NOT NULL,
	NOTICE_STATUS varchar2(30) DEFAULT '정상',
	CREATE_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (NOTICE_NO)
);


CREATE TABLE ORDERS
(
	ORDER_NO number(7,0) NOT NULL,
	CUSTOMER_NO number(7,0) NOT NULL,
	ORDER_DATE date NOT NULL,
	ORDER_STATUS varchar2(30) DEFAULT '접수대기' NOT NULL,
	PRIMARY KEY (ORDER_NO)
);


CREATE TABLE ORDER_DETAIL
(
	ORDER_NO number(7,0) NOT NULL,
	PRODUCT_NO number(7,0) NOT NULL,
	ORDER_QTY number(7,0) NOT NULL
);


CREATE TABLE PASSWORD_HINT
(
	CUSTOMER_NO number(7,0) NOT NULL,
	QUESTION_NO number(7,0) NOT NULL,
	HINT_ANSWER varchar2(100)
);


CREATE TABLE PASSWORD_QEUSTIONS
(
	QUESTION_NO number(7,0) NOT NULL,
	QUESTION_CONTENTS varchar2(1000),
	PRIMARY KEY (QUESTION_NO)
);


CREATE TABLE POINTS_HISTORY
(
	CUSTOMER_NO number(7,0) NOT NULL,
	AMOUNT number(7,0)
);


CREATE TABLE PRODUCTS
(
	PRODUCT_NO number(7,0) NOT NULL,
	CATEGORY_NO number(7,0) NOT NULL,
	PRODUCT_NAME varchar2(100) NOT NULL,
	PRODUCT_PRICE number(7,0) NOT NULL,
	PRODUCT_POINT number(7,0) NOT NULL,
	PRODUCT_DISCOUNT number(7,0) NOT NULL,
	PRODUCT_DETAIL varchar2(1000) NOT NULL,
	-- 품절여부 품절/판매가능
	PRODUCT_STATUS varchar2(30) DEFAULT '정상' NOT NULL,
	PRODUCT_IMG_PORTRAIT_1 varchar2(30) NOT NULL,
	PRODUCT_IMG_PORTRAIT_2 varchar2(30) NOT NULL,
	PRODUCT_BIG_IMG varchar2(30) NOT NULL,
	PRIMARY KEY (PRODUCT_NO)
);


CREATE TABLE PRODUCT_QUESTIONS
(
	QEUSTION_NO number(7,0) NOT NULL,
	PRODUCT_NO number(7,0) NOT NULL,
	CUSTOMER_NO number(7,0) NOT NULL,
	QUESTION_SUBJECT varchar2(30) NOT NULL,
	QUESTION_CONTENTS varchar2(1000) NOT NULL,
	-- 문의글
	-- 답급
	QUESTION_STATUS varchar2(30) DEFAULT '정상' NOT NULL,
	QUESTION_PASSWORD varchar2(30),
	QUESTION_VIEWCOUNT number(7,0) DEFAULT 0,
	CREATE_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (QEUSTION_NO)
);


CREATE TABLE PRODUCT_REVIEWS
(
	REVIEW_NO number(7,0) NOT NULL,
	PRODUCT_NO number(7,0) NOT NULL,
	CUSTOMER_NO number(7,0) NOT NULL,
	REVIEW_CONTENTS varchar2(1000) NOT NULL,
	REVIEW_RECOMMEND_CNT number(7,0) DEFAULT 0 NOT NULL,
	REVIEW_GRADE number(2,1) NOT NULL,
	REVIEW_STATUS varchar2(30) DEFAULT '정상',
	CREATE_DATE date NOT NULL,
	PRIMARY KEY (REVIEW_NO)
);


CREATE TABLE PRODUCT_STOCK
(
	PRODUCT_NO number(7,0) NOT NULL,
	PRODUCT_COLOR varchar2(30) NOT NULL,
	PRODUCT_SIZE varchar2(100) NOT NULL,
	PRODUCT_QTY number(7,0) NOT NULL
);


CREATE TABLE REVIEW_COMMENT
(
	REVIEW_NO number(7,0) NOT NULL,
	ADMIN_ACCOUNT_NO number(7,0) NOT NULL,
	CREATE_DATE date DEFAULT SYSDATE
);


CREATE TABLE REVIEW_RECOMMEND_HISTORY
(
	REVIEW_NO number(7,0) NOT NULL,
	CUSTOMER_NO number(7,0) NOT NULL,
	CREATE_DATE date DEFAULT SYSDATE
);



/* Create Foreign Keys */

ALTER TABLE ANSWERS
	ADD FOREIGN KEY (ADMIN_ACCOUNT_NO)
	REFERENCES ADMIN_ACCOUNTS (ADMIN_ACCOUNT_NO)
;


ALTER TABLE EVENTS
	ADD FOREIGN KEY (ADMIN_ACCOUNT_NO)
	REFERENCES ADMIN_ACCOUNTS (ADMIN_ACCOUNT_NO)
;


ALTER TABLE NOTICES
	ADD FOREIGN KEY (ADMIN_ACCOUNT_NO)
	REFERENCES ADMIN_ACCOUNTS (ADMIN_ACCOUNT_NO)
;


ALTER TABLE REVIEW_COMMENT
	ADD FOREIGN KEY (ADMIN_ACCOUNT_NO)
	REFERENCES ADMIN_ACCOUNTS (ADMIN_ACCOUNT_NO)
;


ALTER TABLE CATEGORIES
	ADD FOREIGN KEY (MAIN_CATEGORY_NO)
	REFERENCES CATEGORIES (CATEGORY_NO)
;


ALTER TABLE PRODUCTS
	ADD FOREIGN KEY (CATEGORY_NO)
	REFERENCES CATEGORIES (CATEGORY_NO)
;


ALTER TABLE CART_ITEMS
	ADD FOREIGN KEY (CUSTOMER_NO)
	REFERENCES CUSTOMERS (CUSTOMER_NO)
;


ALTER TABLE ORDERS
	ADD FOREIGN KEY (CUSTOMER_NO)
	REFERENCES CUSTOMERS (CUSTOMER_NO)
;


ALTER TABLE PASSWORD_HINT
	ADD FOREIGN KEY (CUSTOMER_NO)
	REFERENCES CUSTOMERS (CUSTOMER_NO)
;


ALTER TABLE POINTS_HISTORY
	ADD FOREIGN KEY (CUSTOMER_NO)
	REFERENCES CUSTOMERS (CUSTOMER_NO)
;


ALTER TABLE PRODUCT_QUESTIONS
	ADD FOREIGN KEY (CUSTOMER_NO)
	REFERENCES CUSTOMERS (CUSTOMER_NO)
;


ALTER TABLE PRODUCT_REVIEWS
	ADD FOREIGN KEY (CUSTOMER_NO)
	REFERENCES CUSTOMERS (CUSTOMER_NO)
;


ALTER TABLE REVIEW_RECOMMEND_HISTORY
	ADD FOREIGN KEY (CUSTOMER_NO)
	REFERENCES CUSTOMERS (CUSTOMER_NO)
;


ALTER TABLE ORDER_DETAIL
	ADD FOREIGN KEY (ORDER_NO)
	REFERENCES ORDERS (ORDER_NO)
;


ALTER TABLE PASSWORD_HINT
	ADD FOREIGN KEY (QUESTION_NO)
	REFERENCES PASSWORD_QEUSTIONS (QUESTION_NO)
;


ALTER TABLE CART_ITEMS
	ADD FOREIGN KEY (PRODUCT_NO)
	REFERENCES PRODUCTS (PRODUCT_NO)
;


ALTER TABLE ORDER_DETAIL
	ADD FOREIGN KEY (PRODUCT_NO)
	REFERENCES PRODUCTS (PRODUCT_NO)
;


ALTER TABLE PRODUCT_QUESTIONS
	ADD FOREIGN KEY (PRODUCT_NO)
	REFERENCES PRODUCTS (PRODUCT_NO)
;


ALTER TABLE PRODUCT_REVIEWS
	ADD FOREIGN KEY (PRODUCT_NO)
	REFERENCES PRODUCTS (PRODUCT_NO)
;


ALTER TABLE PRODUCT_STOCK
	ADD FOREIGN KEY (PRODUCT_NO)
	REFERENCES PRODUCTS (PRODUCT_NO)
;


ALTER TABLE ANSWERS
	ADD FOREIGN KEY (QEUSTION_NO)
	REFERENCES PRODUCT_QUESTIONS (QEUSTION_NO)
;


ALTER TABLE REVIEW_COMMENT
	ADD FOREIGN KEY (REVIEW_NO)
	REFERENCES PRODUCT_REVIEWS (REVIEW_NO)
;


ALTER TABLE REVIEW_RECOMMEND_HISTORY
	ADD FOREIGN KEY (REVIEW_NO)
	REFERENCES PRODUCT_REVIEWS (REVIEW_NO)
;



